using FluentMigrator;

namespace AgencyCampaign.Infrastructure.Migrations
{
    // Distingue o lancamento financeiro gerado pela automacao (recebivel/repasse) do digitado manualmente.
    [Migration(202606030006)]
    public sealed class Migration_202606030006_AddFinancialEntryIsAutoGenerated : Migration
    {
        public override void Up()
        {
            Execute.Sql(@"
                ALTER TABLE financialentry ADD COLUMN isautogenerated BOOLEAN NOT NULL DEFAULT FALSE;
            ");
        }

        public override void Down()
        {
            Execute.Sql(@"
                ALTER TABLE financialentry DROP COLUMN IF EXISTS isautogenerated;
            ");
        }
    }
}
