using FluentMigrator;

namespace AgencyCampaign.Infrastructure.Migrations
{
    [Migration(202605230007)]
    public sealed class Migration_202605230007_AddIsAutoGeneratedFlag : Migration
    {
        public override void Up()
        {
            Execute.Sql(@"
                ALTER TABLE opportunityapprovaldiff ADD COLUMN IF NOT EXISTS isautogenerated BOOLEAN NOT NULL DEFAULT FALSE;
                ALTER TABLE opportunityapprovalimpact ADD COLUMN IF NOT EXISTS isautogenerated BOOLEAN NOT NULL DEFAULT FALSE;
            ");
        }

        public override void Down()
        {
            Execute.Sql(@"
                ALTER TABLE opportunityapprovaldiff DROP COLUMN IF EXISTS isautogenerated;
                ALTER TABLE opportunityapprovalimpact DROP COLUMN IF EXISTS isautogenerated;
            ");
        }
    }
}
