using AgencyCampaign.Domain.ValueObjects;
using Archon.Core.Entities;

namespace AgencyCampaign.Domain.Entities
{
    public sealed class FinancialEntry : Entity
    {
        public long AccountId { get; private set; }

        public FinancialAccount? Account { get; private set; }

        public long? CampaignId { get; private set; }

        public Campaign? Campaign { get; private set; }

        public long? CampaignDeliverableId { get; private set; }

        public CampaignDeliverable? CampaignDeliverable { get; private set; }

        public long? SourceProposalId { get; private set; }

        public Proposal? SourceProposal { get; private set; }

        public long? SourceProposalItemId { get; private set; }

        public long? CreatorId { get; private set; }

        public FinancialEntryType Type { get; private set; }

        public FinancialEntryCategory Category { get; private set; }

        public string Description { get; private set; } = string.Empty;

        public decimal Amount { get; private set; }

        public DateTimeOffset DueAt { get; private set; }

        public DateTimeOffset OccurredAt { get; private set; }

        public string? PaymentMethod { get; private set; }

        public string? ReferenceCode { get; private set; }

        public DateTimeOffset? PaidAt { get; private set; }

        public FinancialEntryStatus Status { get; private set; } = FinancialEntryStatus.Pending;

        public string? CounterpartyName { get; private set; }

        public string? Notes { get; private set; }

        public long? SubcategoryId { get; private set; }

        public FinancialSubcategory? Subcategory { get; private set; }

        public long? ParentEntryId { get; private set; }

        public FinancialEntry? ParentEntry { get; private set; }

        public int? InstallmentNumber { get; private set; }

        public int? InstallmentTotal { get; private set; }

        public string? InvoiceNumber { get; private set; }

        public string? InvoiceUrl { get; private set; }

        public DateTimeOffset? InvoiceIssuedAt { get; private set; }

        // Distingue o lancamento gerado pela automacao (recebivel da marca, repasse de creator) do que
        // foi digitado manualmente - para o operador nao editar/apagar por engano um lancamento da automacao.
        public bool IsAutoGenerated { get; private set; }

        // Estorno (D3b): em vez de editar/excluir um lancamento PAGO (bloqueado pela imutabilidade do A2),
        // cria-se uma contrapartida de efeito oposto vinculada ao original. ReversalOfEntryId marca a
        // contrapartida; IsReversed/ReversedAt marcam o original estornado. O par (original + contrapartida)
        // e excluido dos relatorios de competencia e rentabilidade, mas aparece no fluxo de caixa (movimento real).
        public long? ReversalOfEntryId { get; private set; }

        public bool IsReversed { get; private set; }

        public DateTimeOffset? ReversedAt { get; private set; }

        // Cobranca (contas a receber): emissao de boleto/PIX via IntegrationPlatform e baixa por webhook.
        // ChargeId e a chave de correlacao do provedor; ChargeUrl e o link entregue ao pagador.
        public string? ChargeProvider { get; private set; }

        public string? ChargeId { get; private set; }

        public string? ChargeUrl { get; private set; }

        public ChargeStatus ChargeStatus { get; private set; } = ChargeStatus.None;

        public DateTimeOffset? ChargeIssuedAt { get; private set; }

        private FinancialEntry()
        {
        }

        public FinancialEntry(long accountId, FinancialEntryType type, FinancialEntryCategory category, string description, decimal amount, DateTimeOffset dueAt, DateTimeOffset occurredAt, string? paymentMethod = null, string? referenceCode = null, string? counterpartyName = null, string? notes = null, long? campaignId = null, long? campaignDeliverableId = null)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(accountId);
            ArgumentException.ThrowIfNullOrWhiteSpace(description);
            ArgumentOutOfRangeException.ThrowIfNegative(amount);

            AccountId = accountId;
            CampaignId = campaignId;
            CampaignDeliverableId = campaignDeliverableId;
            Type = type;
            Category = category;
            Description = description.Trim();
            Amount = amount;
            DueAt = dueAt.ToUniversalTime();
            OccurredAt = occurredAt.ToUniversalTime();
            PaymentMethod = Normalize(paymentMethod);
            ReferenceCode = Normalize(referenceCode);
            CounterpartyName = Normalize(counterpartyName);
            Notes = Normalize(notes);
        }

        public void Update(long accountId, FinancialEntryType type, FinancialEntryCategory category, string description, decimal amount, DateTimeOffset dueAt, DateTimeOffset occurredAt, string? paymentMethod, string? referenceCode, string? counterpartyName, string? notes, long? campaignId, long? campaignDeliverableId)
        {
            if (Status == FinancialEntryStatus.Paid)
            {
                throw new InvalidOperationException("financialEntry.alreadyPaid");
            }

            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(accountId);
            ArgumentException.ThrowIfNullOrWhiteSpace(description);
            ArgumentOutOfRangeException.ThrowIfNegative(amount);

            AccountId = accountId;
            CampaignId = campaignId;
            CampaignDeliverableId = campaignDeliverableId;
            Type = type;
            Category = category;
            Description = description.Trim();
            Amount = amount;
            DueAt = dueAt.ToUniversalTime();
            OccurredAt = occurredAt.ToUniversalTime();
            PaymentMethod = Normalize(paymentMethod);
            ReferenceCode = Normalize(referenceCode);
            CounterpartyName = Normalize(counterpartyName);
            Notes = Normalize(notes);
        }

        public void ChangeStatus(FinancialEntryStatus status, DateTimeOffset? paidAt = null)
        {
            if (Status == FinancialEntryStatus.Paid && status != FinancialEntryStatus.Paid)
            {
                throw new InvalidOperationException("financialEntry.alreadyPaid");
            }

            Status = status;
            PaidAt = status == FinancialEntryStatus.Paid ? paidAt?.ToUniversalTime() : null;
        }

        // Conciliacao bancaria: baixa o lancamento ao casar com uma transacao do extrato. So lancamentos
        // abertos (Pendente/Vencido) podem ser conciliados; um ja pago nao e candidato.
        public void SettleFromReconciliation(DateTimeOffset paidAt)
        {
            if (Status != FinancialEntryStatus.Pending && Status != FinancialEntryStatus.Overdue)
            {
                throw new InvalidOperationException("financialEntry.notOpenForReconciliation");
            }

            Status = FinancialEntryStatus.Paid;
            PaidAt = paidAt.ToUniversalTime();
        }

        // Reverte a baixa feita pela conciliacao quando o vinculo com a transacao e desfeito. E o unico
        // caminho permitido de Pago -> Pendente; o "despago" manual segue bloqueado em ChangeStatus.
        public void ReopenFromReconciliation()
        {
            Status = FinancialEntryStatus.Pending;
            PaidAt = null;
        }

        public void LinkToProposal(long proposalId)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(proposalId);
            SourceProposalId = proposalId;
        }

        public void LinkToProposalItem(long proposalId, long proposalItemId)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(proposalId);
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(proposalItemId);
            SourceProposalId = proposalId;
            SourceProposalItemId = proposalItemId;
        }

        // Vincula o repasse (CreatorPayout) ao creator, permitindo a baixa automatica quando o
        // CreatorPayment executado e marcado como pago (conciliacao previsto x executado).
        public void LinkToCreator(long creatorId)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(creatorId);
            CreatorId = creatorId;
        }

        public void MarkAsAutoGenerated()
        {
            IsAutoGenerated = true;
        }

        // Marca o lancamento PAGO como estornado. So o pago e estornavel (o pendente se cancela/edita); nao
        // se estorna uma contrapartida nem se reestorna o que ja foi estornado.
        public void MarkAsReversed(DateTimeOffset reversedAt)
        {
            if (Status != FinancialEntryStatus.Paid)
            {
                throw new InvalidOperationException("financialEntry.onlyPaidCanBeReversed");
            }

            if (ReversalOfEntryId.HasValue)
            {
                throw new InvalidOperationException("financialEntry.cannotReverseReversal");
            }

            if (IsReversed)
            {
                throw new InvalidOperationException("financialEntry.alreadyReversed");
            }

            IsReversed = true;
            ReversedAt = reversedAt.ToUniversalTime();
        }

        // Constroi a contrapartida do estorno: efeito oposto (Receivable<->Payable), mesmo valor/conta/campanha/
        // creator, ja PAGA na data do estorno e vinculada ao original via ReversalOfEntryId.
        public FinancialEntry BuildReversalEntry(DateTimeOffset reversedAt, string description)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(description);

            FinancialEntryType opposite = Type == FinancialEntryType.Receivable
                ? FinancialEntryType.Payable
                : FinancialEntryType.Receivable;

            FinancialEntry reversal = new(AccountId, opposite, Category, description, Amount, reversedAt, reversedAt, campaignId: CampaignId, campaignDeliverableId: CampaignDeliverableId);
            reversal.ReversalOfEntryId = Id;
            reversal.CreatorId = CreatorId;
            reversal.ChangeStatus(FinancialEntryStatus.Paid, reversedAt);
            return reversal;
        }

        public void AppendNote(string note)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(note);
            Notes = string.IsNullOrWhiteSpace(Notes) ? note.Trim() : $"{Notes}\n{note.Trim()}";
        }

        public void SetSubcategory(long? subcategoryId)
        {
            SubcategoryId = subcategoryId;
        }

        public void MarkAsInstallment(long? parentEntryId, int installmentNumber, int installmentTotal)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(installmentNumber);
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(installmentTotal);
            if (installmentNumber > installmentTotal)
            {
                throw new ArgumentOutOfRangeException(nameof(installmentNumber), "Installment number cannot exceed total.");
            }

            ParentEntryId = parentEntryId;
            InstallmentNumber = installmentNumber;
            InstallmentTotal = installmentTotal;
        }

        public void SetInvoice(string? invoiceNumber, string? invoiceUrl, DateTimeOffset? issuedAt)
        {
            InvoiceNumber = Normalize(invoiceNumber);
            InvoiceUrl = Normalize(invoiceUrl);
            InvoiceIssuedAt = issuedAt?.ToUniversalTime();
        }

        // Emissao de cobranca (operador): so um recebivel ABERTO (Pendente/Vencido) pode emitir cobranca.
        // Marca como Requested ate o provedor confirmar a emissao no primeiro callback.
        public void RequestCharge(string provider)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(provider);
            if (Type != FinancialEntryType.Receivable)
            {
                throw new InvalidOperationException("financialEntry.charge.onlyReceivable");
            }

            if (Status != FinancialEntryStatus.Pending && Status != FinancialEntryStatus.Overdue)
            {
                throw new InvalidOperationException("financialEntry.charge.notOpen");
            }

            ChargeProvider = provider.Trim();
            ChargeStatus = ChargeStatus.Requested;
        }

        // Correlacao no callback: vincula o lancamento ao id da cobranca no provedor (primeiro callback).
        public void AttachChargeProvider(string provider, string chargeId)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(provider);
            ArgumentException.ThrowIfNullOrWhiteSpace(chargeId);
            ChargeProvider = provider.Trim();
            ChargeId = chargeId.Trim();
        }

        // Provedor confirmou a emissao e devolveu o link (boleto/PIX QR). Nao rebaixa um Paid.
        public void MarkChargeIssued(string? chargeUrl, DateTimeOffset issuedAt)
        {
            ChargeUrl = Normalize(chargeUrl);
            ChargeIssuedAt = issuedAt.ToUniversalTime();
            if (ChargeStatus != ChargeStatus.Paid)
            {
                ChargeStatus = ChargeStatus.Issued;
            }
        }

        // Webhook de pagamento: da baixa no recebivel. Idempotente (retorna false se ja estava pago).
        public bool SettleFromCharge(DateTimeOffset paidAt, string? endToEndId)
        {
            if (Status == FinancialEntryStatus.Paid)
            {
                ChargeStatus = ChargeStatus.Paid;
                return false;
            }

            if (Status != FinancialEntryStatus.Pending && Status != FinancialEntryStatus.Overdue)
            {
                throw new InvalidOperationException("financialEntry.notOpenForReconciliation");
            }

            Status = FinancialEntryStatus.Paid;
            PaidAt = paidAt.ToUniversalTime();
            ChargeStatus = ChargeStatus.Paid;
            if (!string.IsNullOrWhiteSpace(endToEndId))
            {
                ReferenceCode = endToEndId.Trim();
            }

            return true;
        }

        // Cobranca expirada/recusada/cancelada pelo provedor: o recebivel segue aberto para reemissao.
        public void MarkChargeUnpaid(ChargeStatus status, string? reason)
        {
            ChargeStatus = status;
            if (!string.IsNullOrWhiteSpace(reason))
            {
                AppendNote(reason.Trim());
            }
        }

        public void RecalculateOverdue(DateTimeOffset now)
        {
            if (Status == FinancialEntryStatus.Pending && DueAt < now)
            {
                Status = FinancialEntryStatus.Overdue;
                return;
            }

            if (Status == FinancialEntryStatus.Overdue && DueAt >= now)
            {
                Status = FinancialEntryStatus.Pending;
            }
        }

        private static string? Normalize(string? value)
        {
            return string.IsNullOrWhiteSpace(value) ? null : value.Trim();
        }
    }
}
