using AgencyCampaign.Application.Notifications;
using AgencyCampaign.Application.Services;
using AgencyCampaign.Domain.Entities;
using Archon.Application.Services;
using AgencyCampaign.Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AgencyCampaign.Infrastructure.Services
{
    public sealed class FinancialAutoGenerationService : IFinancialAutoGeneration
    {
        private readonly DbContext dbContext;
        private readonly ILogger<FinancialAutoGenerationService>? logger;
        private readonly INotificationService? notificationService;

        public FinancialAutoGenerationService(DbContext dbContext, ILogger<FinancialAutoGenerationService>? logger = null, INotificationService? notificationService = null)
        {
            this.dbContext = dbContext;
            this.logger = logger;
            this.notificationService = notificationService;
        }

        public async Task GenerateForConvertedProposal(Proposal proposal, long campaignId, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(proposal);

            bool alreadyExists = await dbContext.Set<FinancialEntry>()
                .AsNoTracking()
                .AnyAsync(item => item.SourceProposalId == proposal.Id, cancellationToken);

            if (alreadyExists)
            {
                return;
            }

            long? accountId = await ResolveDefaultAccountIdAsync(cancellationToken);
            if (!accountId.HasValue)
            {
                logger?.LogWarning("No active financial account configured; skipping receivable for proposal {ProposalId}.", proposal.Id);
                await NotifyAccountMissingAsync(proposal, cancellationToken);
                return;
            }

            string brandName = await ResolveBrandNameAsync(campaignId, cancellationToken);
            DateTimeOffset dueAt = proposal.ValidityUntil ?? DateTimeOffset.UtcNow.AddDays(30);

            FinancialEntry entry = new(
                accountId.Value,
                FinancialEntryType.Receivable,
                FinancialEntryCategory.BrandReceivable,
                $"Recebível da proposta {proposal.Name}",
                proposal.NetTotalValue,
                dueAt,
                DateTimeOffset.UtcNow,
                paymentMethod: null,
                referenceCode: null,
                counterpartyName: brandName,
                notes: $"Gerado automaticamente a partir da conversão da proposta #{proposal.Id}.",
                campaignId: campaignId);

            entry.LinkToProposal(proposal.Id);
            entry.MarkAsAutoGenerated();

            dbContext.Set<FinancialEntry>().Add(entry);
            try
            {
                await dbContext.SaveChangesAsync(cancellationToken);
            }
            catch (DbUpdateException)
            {
                // Corrida: outro processo ja inseriu o recebivel (unique index uxfinancialentryautoreceivable).
                // Idempotente: trata como no-op se o lancamento agora existe; caso contrario, propaga o erro real.
                dbContext.Entry(entry).State = EntityState.Detached;
                bool nowExists = await dbContext.Set<FinancialEntry>()
                    .AsNoTracking()
                    .AnyAsync(item => item.SourceProposalId == proposal.Id, cancellationToken);
                if (!nowExists)
                {
                    throw;
                }
            }
        }

        public async Task GenerateForPublishedDeliverable(CampaignDeliverable deliverable, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(deliverable);

            if (deliverable.CreatorAmount <= 0)
            {
                return;
            }

            bool alreadyExists = await dbContext.Set<FinancialEntry>()
                .AsNoTracking()
                .AnyAsync(item =>
                    item.CampaignDeliverableId == deliverable.Id &&
                    item.Type == FinancialEntryType.Payable &&
                    item.Category == FinancialEntryCategory.CreatorPayout,
                    cancellationToken);

            if (alreadyExists)
            {
                return;
            }

            var creatorInfo = await dbContext.Set<CampaignCreator>()
                .AsNoTracking()
                .Where(item => item.Id == deliverable.CampaignCreatorId)
                .Select(item => new { item.CreatorId, Name = item.Creator!.StageName ?? item.Creator!.Name })
                .FirstOrDefaultAsync(cancellationToken);

            long? accountId = await ResolveDefaultAccountIdAsync(cancellationToken);
            if (!accountId.HasValue)
            {
                logger?.LogWarning("No active financial account configured; skipping payable for deliverable {DeliverableId}.", deliverable.Id);
                return;
            }

            DateTimeOffset dueAt = (deliverable.PublishedAt ?? DateTimeOffset.UtcNow).AddDays(15);

            FinancialEntry entry = new(
                accountId.Value,
                FinancialEntryType.Payable,
                FinancialEntryCategory.CreatorPayout,
                $"Repasse creator: {deliverable.Title}",
                deliverable.CreatorAmount,
                dueAt,
                DateTimeOffset.UtcNow,
                paymentMethod: null,
                referenceCode: null,
                counterpartyName: creatorInfo?.Name,
                notes: $"Gerado automaticamente após publicação da entrega #{deliverable.Id}.",
                campaignId: deliverable.CampaignId,
                campaignDeliverableId: deliverable.Id);

            if (creatorInfo is not null)
            {
                entry.LinkToCreator(creatorInfo.CreatorId);
            }

            entry.MarkAsAutoGenerated();
            dbContext.Set<FinancialEntry>().Add(entry);
            try
            {
                await dbContext.SaveChangesAsync(cancellationToken);
            }
            catch (DbUpdateException)
            {
                // Corrida: outro processo ja inseriu o repasse (unique index uxfinancialentryautopayout).
                // Idempotente: no-op se o repasse agora existe; caso contrario, propaga o erro real.
                dbContext.Entry(entry).State = EntityState.Detached;
                bool nowExists = await dbContext.Set<FinancialEntry>()
                    .AsNoTracking()
                    .AnyAsync(item => item.CampaignDeliverableId == deliverable.Id
                        && item.Type == FinancialEntryType.Payable
                        && item.Category == FinancialEntryCategory.CreatorPayout, cancellationToken);
                if (!nowExists)
                {
                    throw;
                }
            }
        }

        private async Task<long?> ResolveDefaultAccountIdAsync(CancellationToken cancellationToken)
        {
            return await dbContext.Set<FinancialAccount>()
                .AsNoTracking()
                .Where(item => item.IsActive)
                .OrderByDescending(item => item.IsDefault)
                .ThenBy(item => item.Id)
                .Select(item => (long?)item.Id)
                .FirstOrDefaultAsync(cancellationToken);
        }

        private async Task NotifyAccountMissingAsync(Proposal proposal, CancellationToken cancellationToken)
        {
            if (notificationService is null)
            {
                return;
            }

            try
            {
                await notificationService.Create(KanvasNotifications.ConversionFinancialAccountMissing(proposal), cancellationToken);
            }
            catch (Exception exception)
            {
                logger?.LogError(exception, "Failed to notify missing financial account for proposal {ProposalId}.", proposal.Id);
            }
        }

        private async Task<string> ResolveBrandNameAsync(long campaignId, CancellationToken cancellationToken)
        {
            string? brandName = await dbContext.Set<Campaign>()
                .AsNoTracking()
                .Where(item => item.Id == campaignId)
                .Select(item => item.Brand!.Name)
                .FirstOrDefaultAsync(cancellationToken);

            return brandName ?? "Marca";
        }
    }
}
